[repository]
# The name of the github organization / person owner, e.g. tauffer-consulting.
# Must be in lower-case letters
REGISTRY_NAME = "nathan-vm"

# The name of this Pieces repository
REPOSITORY_NAME = "test_domino_pieces"
REPOSITORY_LABEL = "test_domino_pieces"

# The version of this Pieces release
# Attention: changing this will create a new release
VERSION = "0.2.3"
