from domino.base_piece import BasePiece
from .models import InputModel, OutputModel
import base64
class HTMLPiece(BasePiece):
    
    def piece_function(self, input_data: InputModel ):

        self.logger.info("Starting html_content process...")
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>{input_data.html_title}</title>
        </head>
        <body>
            <h1>Hello, World!</h1>
            <p>This is a simple HTML page generated by a Python function.</p>
        </body>
        </html>
        """

        base64_html = base64.b64encode(html_content.encode('utf-8')).decode('utf-8')

        self.display_result = {
            "file_type": "html",
            "base64_content": base64_html
        }


        return OutputModel(
            html=html_content,
        )